### ISSUE TITLE
Prepare 1.9.1 release

### ISSUE THREAD

**Issue by dbaynard** [commercialhaskell/stack#4177]
This issue should track any requirements to release ~~1.8.1~~ 1.9.1 (stack should be alternating stable/dev for version numbers).

**Comment by dbaynard** [comment]
Currently listed as blocking:

- [ ] #2681 (Fix or help text change)
- [ ] #4088 (Possibly ready to go?)
- [ ] #4148 (Fix or documentation change)

**Comment by dbaynard** [comment]
Integration test failures on lts-11.18 for my arch machine

- [ ] 3520-revision-matching (#3520; #3541)
- [ ] 3942-solver-error-output (#3942; #4114)
- [ ] cabal-solver (3acb3f80a; #116, I think)

**Comment by dbaynard** [comment]
WIP branch https://github.com/dbaynard/stack/tree/release

**Comment by borsboom** [comment]
We can cut a release candidate before #4088 (static binary) is ready, since that only concerns the release process and not stack's functionality.  We can work on that in the RC branch.

For the other two, lets go with help/documentation changes for now rather than delaying too much.

**Comment by dbaynard** [comment]
We're not at a release candidate, yet, so if the review is ok it may even make that.

**Comment by borsboom** [comment]
One more:
* [ ] Fix `upload` integration test on Windows (see https://github.com/commercialhaskell/stack/pull/4167#issuecomment-408639201).

**Comment by Blaisorblade** [comment]
If confirmed, https://github.com/commercialhaskell/stack/issues/4191 seems also relevant.

**Comment by dbaynard** [comment]
- [ ] #4159 would be good — just needs hpack updating to the newest release (the change has been merged but there's no new release yet)

**Comment by borsboom** [comment]
> #4159 would be good — just needs hpack updating to the newest release (the change has been merged but there's no new release yet)
I agree, once it's released we can certainly bump the hpack version in the `v1.9` RC branch.

**Comment by k-bx** [comment]
Looks like the last missing piece was implemented (hpack release and its usage in 
 https://github.com/commercialhaskell/stack/commit/8d1bb774ad2626b62a6f347d10fa1d8e1f00b2e5 ) and we are unblocked for a release :)

**Comment by nh2** [comment]
This is done, right?

**Comment by dbaynard** [comment]
I'm just confirming #4159 — the change has been made; it would be good to make sure the problem is fixed. After that, yes.

**Comment by borsboom** [comment]
Yes, it's done, and 1.9.3 is out now too.
